<?php

/**
 * {@inheritdoc}
 *
 * @see \Drupal\materialize\Materialize::preprocess()
 */
function druda_preprocess_menu__account(&$variables, $hook, $info) {

  $icons = [
    'user.page' => 'account_box',
    'user.logout' => 'cancel_presentation',
    'user.login' => 'exit_to_app'
  ];

  foreach (array_keys($variables['items']) as $route) {
    if (!isset($icons[$route])) {
      continue;
    }
    $variables['items'][$route]['title'] = $icons[$route];
  }
}
