entity_order.entity_order_type.*:
  type: config_entity
  label: 'Entity order type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
