entity_solution.entity_solution_type.*:
  type: config_entity
  label: 'Entity solution type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
